# Generated by Django 6.0 on 2025-12-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='фильм', max_length=100)),
                ('description', models.TextField(default='Описание фильма')),
                ('genre', models.CharField(choices=[('Романтика', 'Романтика'), ('Боевик', 'Боевик')], default='Романтика', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Романтика', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('❤️', '❤️'), ('❤️❤️', '❤️❤️'), ('❤️❤️❤️', '❤️❤️❤️'), ('❤️❤️❤️❤️', '❤️❤️❤️❤️'), ('❤️❤️❤️❤️❤️', '❤️❤️❤️❤️❤️')], default='❤️❤️❤️❤️', max_length=100)),
                ('text', models.TextField(verbose_name='Напишите отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='CineBoard.films')),
                ('choice_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='CineBoard.films')),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='tags',
            field=models.ManyToManyField(to='CineBoard.tag'),
        ),
    ]
